// Catalogue des 93 mesures de l'Annexe A (ISO/IEC 27001:2022) — source de vérité côté serveur.
// Sert à initialiser la Déclaration d'Applicabilité de chaque nouveau projet.
const ANNEX_A = [
  ["5.1","org","Politiques de sécurité de l'information"],["5.2","org","Fonctions et responsabilités liées à la sécurité de l'information"],
  ["5.3","org","Séparation des tâches"],["5.4","org","Responsabilités de la direction"],
  ["5.5","org","Relations avec les autorités"],["5.6","org","Relations avec des groupes de travail spécialisés"],
  ["5.7","org","Renseignement sur les menaces"],["5.8","org","Sécurité de l'information dans la gestion de projet"],
  ["5.9","org","Inventaire des informations et autres actifs associés"],["5.10","org","Utilisation correcte des informations et autres actifs associés"],
  ["5.11","org","Restitution des actifs"],["5.12","org","Classification des informations"],
  ["5.13","org","Marquage des informations"],["5.14","org","Transfert des informations"],
  ["5.15","org","Contrôle d'accès"],["5.16","org","Gestion des identités"],
  ["5.17","org","Informations d'authentification"],["5.18","org","Droits d'accès"],
  ["5.19","org","Sécurité de l'information dans les relations avec les fournisseurs"],["5.20","org","Sécurité de l'information dans les accords conclus avec les fournisseurs"],
  ["5.21","org","Gestion de la sécurité de l'information dans la chaîne d'approvisionnement TIC"],["5.22","org","Surveillance, revue et gestion des changements des services fournisseurs"],
  ["5.23","org","Sécurité de l'information pour l'utilisation de services en nuage"],["5.24","org","Planification et préparation de la gestion des incidents"],
  ["5.25","org","Évaluation des événements de sécurité et prise de décision"],["5.26","org","Réponse aux incidents de sécurité de l'information"],
  ["5.27","org","Tirer des enseignements des incidents de sécurité"],["5.28","org","Collecte de preuves"],
  ["5.29","org","Sécurité de l'information durant une perturbation"],["5.30","org","Préparation des TIC pour la continuité d'activité"],
  ["5.31","org","Exigences légales, statutaires, réglementaires et contractuelles"],["5.32","org","Droits de propriété intellectuelle"],
  ["5.33","org","Protection des enregistrements"],["5.34","org","Protection de la vie privée et des données à caractère personnel"],
  ["5.35","org","Revue indépendante de la sécurité de l'information"],["5.36","org","Conformité aux politiques, règles et normes de sécurité"],
  ["5.37","org","Procédures d'exploitation documentées"],
  ["6.1","ppl","Sélection des candidats"],["6.2","ppl","Conditions d'embauche"],
  ["6.3","ppl","Sensibilisation, apprentissage et formation à la sécurité"],["6.4","ppl","Processus disciplinaire"],
  ["6.5","ppl","Responsabilités après la fin ou le changement d'un emploi"],["6.6","ppl","Engagements de confidentialité ou de non-divulgation"],
  ["6.7","ppl","Travail à distance"],["6.8","ppl","Signalement des événements de sécurité de l'information"],
  ["7.1","phy","Périmètres de sécurité physique"],["7.2","phy","Entrées physiques"],
  ["7.3","phy","Sécurisation des bureaux, locaux et installations"],["7.4","phy","Surveillance de la sécurité physique"],
  ["7.5","phy","Protection contre les menaces physiques et environnementales"],["7.6","phy","Travail dans les zones sécurisées"],
  ["7.7","phy","Bureau propre et écran verrouillé"],["7.8","phy","Emplacement et protection du matériel"],
  ["7.9","phy","Sécurité des actifs hors des locaux"],["7.10","phy","Supports de stockage"],
  ["7.11","phy","Services supports"],["7.12","phy","Sécurité du câblage"],
  ["7.13","phy","Maintenance du matériel"],["7.14","phy","Mise au rebut ou réutilisation sécurisée du matériel"],
  ["8.1","tech","Terminaux finaux des utilisateurs"],["8.2","tech","Droits d'accès privilégiés"],
  ["8.3","tech","Restriction d'accès à l'information"],["8.4","tech","Accès au code source"],
  ["8.5","tech","Authentification sécurisée"],["8.6","tech","Gestion des capacités"],
  ["8.7","tech","Protection contre les programmes malveillants"],["8.8","tech","Gestion des vulnérabilités techniques"],
  ["8.9","tech","Gestion de la configuration"],["8.10","tech","Suppression des informations"],
  ["8.11","tech","Masquage des données"],["8.12","tech","Prévention de la fuite de données"],
  ["8.13","tech","Sauvegarde des informations"],["8.14","tech","Redondance des moyens de traitement de l'information"],
  ["8.15","tech","Journalisation"],["8.16","tech","Activités de surveillance"],
  ["8.17","tech","Synchronisation des horloges"],["8.18","tech","Utilisation de programmes utilitaires à privilèges"],
  ["8.19","tech","Installation de logiciels sur les systèmes en exploitation"],["8.20","tech","Sécurité des réseaux"],
  ["8.21","tech","Sécurité des services réseau"],["8.22","tech","Cloisonnement des réseaux"],
  ["8.23","tech","Filtrage web"],["8.24","tech","Utilisation de la cryptographie"],
  ["8.25","tech","Cycle de vie de développement sécurisé"],["8.26","tech","Exigences de sécurité des applications"],
  ["8.27","tech","Principes d'ingénierie et d'architecture sécurisées"],["8.28","tech","Codage sécurisé"],
  ["8.29","tech","Tests de sécurité dans le développement et l'acceptation"],["8.30","tech","Développement externalisé"],
  ["8.31","tech","Séparation des environnements de dev, test et production"],["8.32","tech","Gestion des changements"],
  ["8.33","tech","Informations de test"],["8.34","tech","Protection des SI pendant les tests d'audit"],
].map(([ref,theme,title])=>({ref,theme,title}));

module.exports = { ANNEX_A };
